text=input("Enter any text =>")
print(text)
print(text.upper())
print(text.lower())
print(text.startswith("a"))
print(text.endswith("a"))
print(text.capitalize())
print(text.replace("p","t"))
print(text.index('e',1,9))
print(text.count(text,0))
